openapi: 3.0.1
info:
  title: Palomma API
  version: ''
paths:
  /payment-requests:
    post:
      operationId: paymentRequest_post
      tags:
        - PaymentRequest
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePaymentRequestResponse'
              examples:
                Example1:
                  value:
                    id: 8f59ec29-3e8a-4cbd-b4c0-4f480b1fac15
                    payment_url: >-
                      https://www.sandbox-pay.palomma.com/?transaccion=8f59ec29-3e8a-4cbd-b4c0-4f480b1fac15
        '400':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      errorName:
                        type: string
                        enum:
                          - BadRequestError
                      content:
                        $ref: '#/components/schemas/ErrorBody'
        '401':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      errorName:
                        type: string
                        enum:
                          - InvalidApiKeyError
      summary: Crear solicitud de pago
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount_cents:
                  type: integer
                  description: >-
                    El monto de la transacción en centavos. Debe ser mayor a
                    300.000, y menor a 80.000.000.
                  example: 300000
                description:
                  type: string
                  description: >-
                    Descripción opcional para la solicitud de pago. Puede ser
                    una referencia de pago o algún texto breve que describa la
                    transacción. El usuario nunca verá esta descripción.
                redirect_url:
                  type: string
                  description: >-
                    El URL al que se redirecciona al usuario cuando haya
                    terminado el pago a través de Palomma. Sobreescribe el URL
                    de redirección configurado en el
                    [Onboarding](/general/onboarding).
                ttl:
                  type: integer
                  description: >-
                    El tiempo en segundos que puede quedar la transacción en
                    estado pendiente antes de ser cancelada. Si no se especifica
                    y no está especificado para tu comercio en el
                    [Onboarding](/general/onboarding), la solicitud de pago no
                    expira.
                enforced_document_number:
                  type: string
                  description: >-
                    Impone que la cuenta de banco vinculada a Palomma para
                    realizar el pago esté asociada con la cédula especificada.
                    Principalmente util por temas de cumplimento de normativas.
                    Utilice este campo si necesita verificar que la cuenta de
                    banco que se vincula a Palomma para realizar el pago la
                    pertenece al usuario que está registrado en su servicio. Si
                    la cuenta de banco no está asociada con la cédula
                    especificada, el usuario no podrá completar su pago. Si no
                    se especifica, no se verifica la cédula. Esta verificación
                    aún no está activa con todos los bancos disponibles.
              required:
                - amount_cents
            examples:
              Example1:
                value:
                  amount_cents: 300000
                  description: Pay subscription
                  redirect_url: https://palomma.com
              Example2:
                value:
                  amount_cents: 300000
                  description: Pay subscription
                  redirect_url: https://palomma.com
  /payment-requests/{transactionId}:
    get:
      operationId: paymentRequest_get
      tags:
        - PaymentRequest
      parameters:
        - name: transactionId
          in: path
          description: Un identificador único para la solicitud de pago.
          required: true
          schema:
            $ref: '#/components/schemas/TransactionId'
          examples:
            Example1:
              value: 8f59ec29-3e8a-4cbd-b4c0-4f480b1fac15
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentRequest'
              examples:
                Example1:
                  value:
                    id: 8f59ec29-3e8a-4cbd-b4c0-4f480b1fac15
                    status: PENDING
                    amount_cents: 300000
                    description: Pay subscription
        '400':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      errorName:
                        type: string
                        enum:
                          - BadRequestError
                      content:
                        $ref: '#/components/schemas/ErrorBody'
        '401':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      errorName:
                        type: string
                        enum:
                          - InvalidApiKeyError
        '403':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      errorName:
                        type: string
                        enum:
                          - ForbiddenError
                      content:
                        $ref: '#/components/schemas/ErrorBody'
        '404':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      errorName:
                        type: string
                        enum:
                          - PaymentRequestNotFoundError
      summary: Revisar estado del pago
components:
  schemas:
    TransactionId:
      type: string
    ErrorBody:
      type: object
      properties:
        message:
          type: string
    CreatePaymentRequestResponse:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/TransactionId'
          description: Un identificador único para la solicitud de pago.
        payment_url:
          type: string
          description: >-
            El enlace de pago al que se debe redirigir al usuario para realizar
            el pago.
          example: >-
            https://www.sandbox-pay.palomma.com/?transaccion=8f59ec29-3e8a-4cbd-b4c0-4f480b1fac15
      required:
        - id
        - payment_url
    PaymentRequest:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/TransactionId'
          description: Un identificador único para la solicitud de pago.
        status:
          type: string
          description: >-
            El estado actual de la solicitud de pago. [Posibles
            estados.](/general/estados)
          example: PENDING
        amount_cents:
          type: integer
          description: El monto de la transacción en centavos.
          example: 300000
        description:
          type: string
          description: >-
            Descripción opcional para la solicitud de pago. Puede ser una
            referencia de pago o algún texto breve que describa la transacción.
        enforced_document_number:
          type: string
          description: >-
            La cédula que debe corresponder a la asociada con la cuenta de banco
            de la cual se hace el pago. Si no se especificó, no se verifica la
            cédula.
      required:
        - id
        - status
        - amount_cents
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
servers:
  - url: https://api.pay.palomma.com/
    description: Production
  - url: https://api.sandbox-pay.palomma.com/
    description: Sandbox
